name: Release

on:
  push:
    branches:
      - 'test*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Display OS and architecture
        run: |
          lsb_release -a
          uname -m
      # - name: Build with Maven
      #   run: mvn -B package -DskipTests
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "standalone/target/bkvm-*.zip"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     generateReleaseNotes: true
